// Add plantable blocks
// example: minecraft:potato
minecraft:wheat_seeds
minecraft:pumpkin_seeds
minecraft:melon_seeds
minecraft:nether_wart
minecraft:beetroot_seeds
minecraft:potato
minecraft:carrot