#This config allows you to add or remove folders or single files as Data-/Resourcepacks
#For that simply specify the file path to the folder/file relative to your .minecraft folder
[resourcepacks]
required = [    
    "gresourcepacks/"
]

[datapacks]
required = [
    "gdatapacks/"
]

optional = [
    "global_packs/optional_data/"
]